@baseUrl = http://localhost:3001/api/v2

### Read all users
GET {{baseUrl}}/users

### Create a new user
POST {{baseUrl}}/users
Content-Type: application/json

{
    "username": "AB",
    "email": "ab@example.com",
    "password": "pass123"
}

### Update a user
PUT {{baseUrl}}/users/6a9e723161b786b0d7f338d5
Content-Type: application/json

{
  "username": "AB_Updated",
  "email": "ab_new@example.com",
  "password": "pass123"
}
### Delete a user
DELETE {{baseUrl}}/users/6a9e723161b786b0d7f338d5

