### Read all users
GET http://localhost:3001/api/v1/users

### Create a new user
POST http://localhost:3001/api/v1/users
Content-Type: application/json

{
    "username": "D",
    "email": "dd@example.com",
    "password": "pass123"
}

### Update a user
PUT http://localhost:3001/api/v1/users/1
Content-Type: application/json

{
    "username": "AA",
    "email": "a@example.com",
    "password": "pass123"
}

### Delete a user
DELETE http://localhost:3001/api/v1/users/1

### Trigger centralize error handliing middleware
POST http://localhost:3001/api/v1/users
Content-Type: application/json
{
    "username": "AA",
    "email": "a@example.com",
    "password": "pass123"
}